version: "3.8"

services:
    auth:
        build: ./auth
        ports:
            - "3000:3000"
        env_file:
            - ./auth/.env
        networks:
            - ecommerce

    api-gateway:
        build: ./api-gateway
        ports:
            - "3003:3003"
        # environment:
        #     - RABBITMQ_URL=amqp://rabbitmq:5672
        networks:
            - ecommerce

networks:
    ecommerce:
        driver: bridge
